### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#786]
- [ ] FAAS
      creating a special worker that exposes an API for the algorithm.
     so the user will be able to call directly to the algorithm functions.
example:
      /api/faas/my-alg/
```
method: 'calc'
entryPoint: 'main.py'
```
This will increase performance, no overhead of creating a pipeline.

- [ ] Any Image
The worker will create container and read it's result
```
    image: any
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
```
- [ ] Show used resources for an algorithm in job level.
- [ ] Add creation/updated time for algorithm/pipeline.
- [ ] Retry on pipeline level.
- [ ] Health API (including dashboard).
- [ ] More pipeline statistics, include in  dashboard and API (can use promateus)
- [ ] Show how many workers were involved during the pipeline run. how the tasks were distributed among workers([worker1: 5 tasks], [workers2: 8 tasks])
- [ ] Add option to shut-down workers (in case the user wants to change env vars).
- [ ] Trace node, algorithm level.
- [ ] Push notifications on build or pipeline completed (web, email)
